<?php
namespace library\doctrine\Entities;
/** @Entity 
 *	@Table(name="patient_data")
 */
class Patient
{
	/**
	 * @Id 
	 * @Column(type="integer") 
	 * @GeneratedValue(strategy="AUTO")
	*/
	protected $pid;

	// This is the ID column in the patient_data table which is autogenerated not truly the primary key
	/** 
	 * @Column(type="integer",name="id") 
	*/
	protected $id;

	/** @Column(type="string",length=255) */
	protected $fname;

	function getId()
	{
		return $this->id;
	}


	/** @Column(type="string",length=255) */
	protected $lname;

	/** @Column(type="string",length=255) */
	protected $mname;


	/** @Column(type="string",length=255) */
	protected $sex;

	/** @Column(type="date") */
	protected $DOB;

	function getDOB()
	{
		return $this->dob;
	}

	/** @Column(type="datetime", name="date") */
	protected $ts;


	function display()
	{


		echo $this->lname .',' . $this->fname . ' ' . $this->mname . '<br>';
		echo $this->pid . '<br>';
		echo $this->sex .'<br>';
		echo $this->id .'<br>';
		echo $this->DOB->format('m-d-y');
		echo '<br>';
		echo $this->ts->format('m-d-y h:i:s');
		echo '<br>';
		

	}
}
?>
