<?php
define('CONTENT_TYPE_NORMAL','NORMAL');
define('CONTENT_TYPE_ABNORMAL','ABNORMAL');
define('CONTENT_TYPE_TRAIT','TRAIT');
define('CONTENT_TYPE_MEASUREMENT','MEASUREMENT');


define('CONTENT_TYPE_CONTEXT','CONTEXT');

        
?>
