<?php

require_once("checkBillingAuth.php");
require_once("billingUtilities.php");
require_once("$doctrineroot/common/checkDocument.php");
require_once("$doctrineroot/ui/DocumentEditor/Billing/FeeSheetRendering.php");

if(isset($_SESSION['pid']))
{
    $patID=$_SESSION['pid'];
    $pat=$em->getRepository('library\doctrine\Entities\Patient')->find($patID);
    
}

if($doc->getOEMREncounter()==null)
{
    
    $encounter = rand();
    $DOS=$doc->getDateofservice();
    $em->beginTransaction();
    $prov=$doctrineUser->getID();
    $OEMREnc=new library\doctrine\Entities\OEMREncounter($pat,$DOS,$encounter,$prov,"normal");

    // Fix hard coded cat id and other info
    $OEMREnc->setCatid(5);
    $OEMREnc->setReason("Autogenerated for document:".$doc->getUUID());
    $OEMREnc->setFacility_id(3);
    $OEMREnc->setBilling_facility(3);
    
    $em->persist($OEMREnc);
    $em->flush();

    $Enc=$em->getRepository('library\doctrine\Entities\OEMREncounter')->findOneBy(array('encounter'=>$encounter,'patient'=>$patID));
   $em->refresh($Enc);
    $fid=$Enc->getID();

    error_log(count($res));
    error_log("Encounter Form ID".$fid);
    $OEMRForm= new library\doctrine\Entities\OEMRForm($pat,$doctrineUser->getUsername(),$encounter,$fid,"New Patient Encounter","newpatient");
    $OEMRForm->setEncounter($encounter);
    $em->persist($OEMRForm);
    
    $em->flush();

    $doc->setOEMREncounter($Enc);
    $em->flush();
    $em->commit();
}

// create a billing entries for the problems in this document.
$problems=syncProblems($em,$doc);

if(isset($_REQUEST['codeType']))
{
    if(isset($_REQUEST['codeVal']))
    {
        $codeType=$_REQUEST['codeType'];
        $codeVal=$_REQUEST['codeVal'];
        // we need to create or change the procedure code for this request
        require_once("CPTUtilities.php");
        billForCPT($em,$doc,$codeVal,$codeType,$problems);
        
    }
    $_SESSION['encounter']=$doc->getOEMREncounter()->getEncounter();
}


$DOM = new DOMDocument("1.0","utf-8");
$table=FeeSheetRender($DOM,$DOM,$doc->getOEMREncounter());

echo $DOM->saveXML($table);
?>
