<?php

require_once("checkBillingAuth.php");
require_once("billingUtilities.php");
require_once("$doctrineroot/common/checkDocument.php");
require_once("$doctrineroot/ui/DocumentEditor/Billing/FeeSheetRendering.php");

if(isset($_SESSION['pid']))
{
    $patID=$_SESSION['pid'];
    $pat=$em->getRepository('library\doctrine\Entities\Patient')->find($patID);
    
}

if($doc->getOEMREncounter()==null)
{
    // No Encounter set, need to create one.


    $_POST['mode']="new";

    // TODO: fix hard coded values for billing

    $_POST['facility_id']=3;
    $_POST['billing_facility']=3;
  
    $GLOBALS['OE_SITE_DIR']="/var/www/openemr/sites/default";
    
    $encounter = 99999;
    $DOS=$doc->getDateofservice();
    $em->beginTransaction();
    $OEMREnc=new library\doctrine\Entities\OEMREncounter($pat,$DOS,$encounter,"normal");

    // Fix hard coded cat id and other info
    $OEMREnc->setCatid(5);
    $OEMREnc->setReason("Autogenerated for document:".$doc->getUUID());
    $OEMREnc->setFacility_id(3);
    $OEMREnc->setBilling_facility(3);
    
    $em->persist($OEMREnc);
    $em->flush();

    $fid=$OEMREnc->getID();

    error_log("Encounter Form ID".$fid);
    $OEMRForm= new library\doctrine\Entities\OEMRForm($pat,$doctrineUser->getUsername(),$encounter,$fid,"New Patient Encounter","newpatient");
    $OEMRForm->setEncounter($encounter);
    $em->persist($OEMRForm);
    
    $em->flush();
//    require_once("/var/www/openemr/interface/forms/newpatient/saveDoctrine.php");
//    $OEMREnc=$em->getRepository('library\doctrine\Entities\OEMREncounter')->findOneBy(array('encounter'=>$_SESSION['encounter'],'patient'=>$patID));               

//    $doc->setOEMREncounter($OEMREnc);

    $em->commit();
}

// create a billing entries for the problems in this document.
//$problems=syncProblems($em,$doc);

if(isset($_REQUEST['codeType']))
{
    if(isset($_REQUEST['codeVal']))
    {
        $codeType=$_REQUEST['codeType'];
        $codeVal=$_REQUEST['codeVal'];
        // we need to create or change the procedure code for this request
        require_once("CPTUtilities.php");
        billForCPT($em,$doc,$codeVal,$codeType,$problems);
        
    }
    $_SESSION['encounter']=$doc->getOEMREncounter()->getEncounter();
}


$DOM = new DOMDocument("1.0","utf-8");
//$table=FeeSheetRender($DOM,$DOM,$doc->getOEMREncounter());

//echo $DOM->saveXML($table);
?>
